# Generated by Django 4.0.6 on 2022-10-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_cmsslider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(upload_to='sliderimage/', verbose_name='Картинки для слайдера'),
        ),
    ]
