# Generated by Django 4.0.6 on 2022-10-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_commentcrm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentcrm',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='statuscrm',
            options={'verbose_name': 'Cтатус', 'verbose_name_plural': 'Cтатусы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.statuscrm', verbose_name='Статус'),
        ),
    ]
